version: "3"

networks:
  corp:
    driver: bridge

services:
  account_web:
    container_name: account
    networks:
      - corp
    restart: always
    build:
      context: .
      dockerfile: cicd/app/Dockerfile
      args:
        - TENANT=cl
        - ENV=stage
        - APP=account
        - BASE_HREF=/account/

  products_web:
    container_name: products
    networks:
      - corp
    restart: always
    build:
      context: .
      dockerfile: cicd/app/Dockerfile
      args:
        - TENANT=cl
        - ENV=stage
        - APP=products
        - BASE_HREF=/products/

  proxy_reverse:
    container_name: proxy-reverse
    networks:
      - corp
    restart: always
    build:
      context: .
      dockerfile: cicd/proxy-reverse/Dockerfile
    depends_on:
      - account_web
      - products_web
    ports:
      - "80:80"
